CREATE TABLE `car_behavior_info` (
  `id` varchar(50) CHARACTER SET utf8 NOT NULL COMMENT '主键id',
  `account_id` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `ai_in_car_id` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `app_id` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `app_name` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `app_version` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `car_brand` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `car_vin` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `device_brand` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `device_id` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `device_os_name` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `device_os_ver` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `event_code` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `event_time_2` varchar(255) DEFAULT NULL,
  `event_time` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `event_type` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `hardware_ver` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `info_str` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `language` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `latitude` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `longitude` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `mcu_software_ver` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `net_type` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `platform` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `session_time` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `system_result` varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  `create_time` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '数据创建时间',
  `app_start` varchar(255) DEFAULT '',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `create_time` (`create_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='car_behavior的数据信息';